name: Generate Chart

on:
  push:
    branches: [ main ]

jobs:
  generate_chart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib

    - name: Generate chart
      run: |
        python script.py

    - name: Commit and push chart
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sociotype_chart.png
        git commit -m "Update chart" || echo "No changes to commit"
        git push || echo "No changes to push"
